package com.fullsteam.model;

import com.fullsteam.games.GameConfig;
import io.micronaut.core.annotation.Introspected;

import java.util.List;
import java.util.Optional;

@Introspected
public class GamePresets {

    // --- Rules Presets ---
    public static final Rules TEAM_BATTLE_RULES = Rules.builder()
            .flagsPerTeam(0)
            .scoreStyle(ScoreStyle.TOTAL_KILLS)
            .victoryCondition(VictoryCondition.TIME_LIMIT)
            .scoreLimit(50)
            .timeLimit(600.0)
            .suddenDeath(true)
            .respawnMode(RespawnMode.DELAYED)
            .respawnDelay(5.0)
            .waveRespawnInterval(30.0)
            .maxLives(-1)
            .kothZones(0)
            .kothPointsPerSecond(1.0)
            .build();

    public static final Rules FFA_RULES = Rules.builder()
            .flagsPerTeam(0)
            .scoreStyle(ScoreStyle.TOTAL_KILLS)
            .victoryCondition(VictoryCondition.SCORE_LIMIT)
            .scoreLimit(25)
            .suddenDeath(false)
            .respawnMode(RespawnMode.DELAYED)
            .respawnDelay(3.0)
            .waveRespawnInterval(30.0)
            .maxLives(-1)
            .kothZones(0)
            .kothPointsPerSecond(1.0)
            .build();

    public static final Rules CTF_RULES = Rules.builder()
            .flagsPerTeam(1)
            .scoreStyle(ScoreStyle.OBJECTIVE)
            .victoryCondition(VictoryCondition.SCORE_LIMIT)
            .scoreLimit(5)
            .suddenDeath(true)
            .respawnMode(RespawnMode.WAVE)
            .respawnDelay(5.0)
            .waveRespawnInterval(20.0)
            .maxLives(-1)
            .kothZones(0)
            .kothPointsPerSecond(1.0)
            .build();

    public static final Rules DOMINATION_RULES = Rules.builder()
            .flagsPerTeam(0)
            .scoreStyle(ScoreStyle.OBJECTIVE)
            .victoryCondition(VictoryCondition.SCORE_LIMIT)
            .scoreLimit(200)
            .suddenDeath(true)
            .respawnMode(RespawnMode.DELAYED)
            .respawnDelay(4.0)
            .waveRespawnInterval(30.0)
            .maxLives(-1)
            .kothZones(3)
            .kothPointsPerSecond(2.0)
            .build();

    public static final Rules ELIMINATION_RULES = Rules.builder()
            .flagsPerTeam(0)
            .scoreStyle(ScoreStyle.TOTAL_KILLS)
            .victoryCondition(VictoryCondition.ELIMINATION)
            .scoreLimit(50)
            .suddenDeath(false)
            .lockGameAfterSeconds(15.0)
            .respawnMode(RespawnMode.LIMITED)
            .respawnDelay(0.0)
            .waveRespawnInterval(30.0)
            .maxLives(1)
            .kothZones(0)
            .kothPointsPerSecond(1.0)
            .enableRandomEvents(true)
            .randomEventInterval(60.0)
            .randomEventIntervalVariance(0.4)
            .eventWarningDuration(4.0)
            .addHeadquarters(false)
            .build();

    public static final Rules STOCK_BATTLE_RULES = Rules.builder()
            .flagsPerTeam(0)
            .scoreStyle(ScoreStyle.TOTAL_KILLS)
            .victoryCondition(VictoryCondition.ELIMINATION)
            .scoreLimit(50)
            .suddenDeath(true)
            .respawnMode(RespawnMode.LIMITED)
            .respawnDelay(3.0)
            .waveRespawnInterval(30.0)
            .maxLives(5)
            .kothZones(0)
            .kothPointsPerSecond(1.0)
            .build();

    public static final Rules HEADQUARTERS_ASSAULT_RULES = Rules.builder()
            .flagsPerTeam(0)
            .scoreStyle(ScoreStyle.TOTAL)
            .victoryCondition(VictoryCondition.SCORE_LIMIT)
            .scoreLimit(1000)
            .suddenDeath(false)
            .respawnMode(RespawnMode.WAVE)
            .respawnDelay(5.0)
            .waveRespawnInterval(25.0)
            .maxLives(-1)
            .kothZones(0)
            .addHeadquarters(true)
            .headquartersMaxHealth(5000.0)
            .headquartersPointsPerDamage(0.01)
            .headquartersDestructionBonus(1000)
            .headquartersDestructionEndsGame(true)
            .build();

    public static final Rules CHAOS_MODE_RULES = Rules.builder()
            .flagsPerTeam(0)
            .scoreStyle(ScoreStyle.TOTAL)
            .victoryCondition(VictoryCondition.TIME_LIMIT)
            .scoreLimit(100)
            .timeLimit(600.0)
            .suddenDeath(true)
            .respawnMode(RespawnMode.DELAYED)
            .respawnDelay(3.0)
            .waveRespawnInterval(30.0)
            .maxLives(-1)
            .kothZones(2)
            .kothPointsPerSecond(1.5)
            .addHeadquarters(false)
            .headquartersMaxHealth(1000.0)
            .headquartersPointsPerDamage(0.1)
            .headquartersDestructionBonus(100)
            .headquartersDestructionEndsGame(false)
            .enableRandomEvents(true)
            .randomEventInterval(15.0)
            .eventWarningDuration(5.0)
            .meteorShowerDensity(EntityWorldDensity.CHOKED)
            .volcanicEruptionDensity(EntityWorldDensity.DENSE)
            .ionStormDensity(EntityWorldDensity.DENSE)
            .earthquakeDensity(EntityWorldDensity.DENSE)
            .blizzardDensity(EntityWorldDensity.DENSE)
            .build();

    public static final Rules ODDBALL_RULES = Rules.builder()
            .flagsPerTeam(0)
            .scoreStyle(ScoreStyle.OBJECTIVE)
            .victoryCondition(VictoryCondition.SCORE_LIMIT)
            .scoreLimit(1000)
            .suddenDeath(true)
            .respawnMode(RespawnMode.DELAYED)
            .respawnDelay(4.0)
            .waveRespawnInterval(30.0)
            .maxLives(-1)
            .kothZones(0)
            .kothPointsPerSecond(1.0)
            .enableRandomEvents(false)
            .randomEventInterval(40.0)
            .eventWarningDuration(3.0)
            .enableOddballNpcs(true)
            .rampageBallCount(1)
            .seekerBallCount(2)
            .oddballNpcPointsPerDamage(0.1)
            .build();

    public static final Rules KINGPIN_RULES = Rules.builder()
            .flagsPerTeam(0)
            .scoreStyle(ScoreStyle.OBJECTIVE)
            .victoryCondition(VictoryCondition.SCORE_LIMIT)
            .scoreLimit(90)
            .suddenDeath(true)
            .respawnMode(RespawnMode.DELAYED)
            .respawnDelay(3.0)
            .maxLives(-1)
            .kothZones(1)
            .kothPointsPerSecond(1.0)
            .headquartersMaxHealth(1000.0)
            .headquartersPointsPerDamage(0.1)
            .headquartersDestructionBonus(0)
            .headquartersDestructionEndsGame(false)
            .enableRandomEvents(true)
            .randomEventInterval(60.0)
            .eventWarningDuration(4.0)
            .meteorShowerDensity(EntityWorldDensity.SPARSE)
            .volcanicEruptionDensity(EntityWorldDensity.SPARSE)
            .ionStormDensity(EntityWorldDensity.SPARSE)
            .earthquakeDensity(EntityWorldDensity.SPARSE)
            .blizzardDensity(EntityWorldDensity.SPARSE)
            .enableVip(false)
            .obstacleDensity(EntityWorldDensity.DENSE)
            .pointsPerFlagCapture(1)
            .enableRandomWeapons(true)
            .build();

    public static final Rules VIP_ASSASSINATION_RULES = Rules.builder()
            .flagsPerTeam(0)
            .scoreStyle(ScoreStyle.OBJECTIVE)
            .victoryCondition(VictoryCondition.SCORE_LIMIT)
            .scoreLimit(10)
            .suddenDeath(true)
            .respawnMode(RespawnMode.WAVE)
            .respawnDelay(5.0)
            .waveRespawnInterval(20.0)
            .maxLives(-1)
            .kothZones(0)
            .kothPointsPerSecond(0.5)
            .addHeadquarters(false)
            .headquartersMaxHealth(1000.0)
            .headquartersPointsPerDamage(0.1)
            .headquartersDestructionBonus(100)
            .headquartersDestructionEndsGame(false)
            .enableRandomEvents(true)
            .randomEventInterval(50.0)
            .eventWarningDuration(4.0)
            .meteorShowerDensity(EntityWorldDensity.CHOKED)
            .volcanicEruptionDensity(EntityWorldDensity.SPARSE)
            .ionStormDensity(EntityWorldDensity.DENSE)
            .earthquakeDensity(EntityWorldDensity.SPARSE)
            .blizzardDensity(EntityWorldDensity.SPARSE)
            .enableVip(true)
            .obstacleDensity(EntityWorldDensity.DENSE)
            .build();

    public static final Rules LAST_STAND_RULES = Rules.builder()
            .flagsPerTeam(0)
            .scoreStyle(ScoreStyle.TOTAL_KILLS)
            .victoryCondition(VictoryCondition.SCORE_LIMIT)
            .scoreLimit(20)
            .suddenDeath(false)
            .respawnMode(RespawnMode.LAST_STANDING)
            .respawnDelay(0.0)
            .waveRespawnInterval(30.0)
            .maxLives(-1)
            .kothZones(0)
            .kothPointsPerSecond(1.0)
            .build();

    // --- Game Preset Container DTO ---
    @Introspected
    public record Preset(String id, String label, GameConfig config) {}

    // --- Presets List ---
    public static final List<Preset> ALL_PRESETS = List.of(
            new Preset("team-battle", "⚔️ Team Battle", GameConfig.builder()
                    .maxPlayers(20)
                    .teamCount(4)
                    .worldWidth(2500)
                    .worldHeight(2500)
                    .playerMaxHealth(100)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(TEAM_BATTLE_RULES)
                    .build()),
            new Preset("ffa", "💥 Free For All", GameConfig.builder()
                    .maxPlayers(10)
                    .teamCount(0)
                    .worldWidth(1500)
                    .worldHeight(1500)
                    .playerMaxHealth(100)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(FFA_RULES)
                    .build()),
            new Preset("ctf", "🚩 Capture The Flag", GameConfig.builder()
                    .maxPlayers(24)
                    .teamCount(3)
                    .worldWidth(2500)
                    .worldHeight(2500)
                    .playerMaxHealth(100)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(CTF_RULES)
                    .build()),
            new Preset("domination", "👑 Domination", GameConfig.builder()
                    .maxPlayers(15)
                    .teamCount(3)
                    .worldWidth(2200)
                    .worldHeight(2200)
                    .playerMaxHealth(100)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(DOMINATION_RULES)
                    .build()),
            new Preset("elimination", "🎯 Battle Royale", GameConfig.builder()
                    .maxPlayers(50)
                    .teamCount(0)
                    .worldWidth(4000)
                    .worldHeight(4000)
                    .playerMaxHealth(250)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(ELIMINATION_RULES)
                    .build()),
            new Preset("stock-battle", "❤️ Stock Battle", GameConfig.builder()
                    .maxPlayers(16)
                    .teamCount(4)
                    .worldWidth(1800)
                    .worldHeight(1800)
                    .playerMaxHealth(100)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(STOCK_BATTLE_RULES)
                    .build()),
            new Preset("headquarters-assault", "🏛️ Headquarters", GameConfig.builder()
                    .maxPlayers(16)
                    .teamCount(2)
                    .worldWidth(4000)
                    .worldHeight(1000)
                    .playerMaxHealth(100)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(HEADQUARTERS_ASSAULT_RULES)
                    .build()),
            new Preset("chaos-mode", "🌋 Chaos Mode", GameConfig.builder()
                    .maxPlayers(15)
                    .teamCount(3)
                    .worldWidth(3000)
                    .worldHeight(2000)
                    .playerMaxHealth(100)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(CHAOS_MODE_RULES)
                    .build()),
            new Preset("oddball", "⭐ Oddball", GameConfig.builder()
                    .maxPlayers(12)
                    .teamCount(4)
                    .worldWidth(2500)
                    .worldHeight(2500)
                    .playerMaxHealth(100)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(ODDBALL_RULES)
                    .build()),
            new Preset("vip-assassination", "🎖️ VIP", GameConfig.builder()
                    .maxPlayers(15)
                    .teamCount(3)
                    .worldWidth(2200)
                    .worldHeight(2200)
                    .playerMaxHealth(100)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(VIP_ASSASSINATION_RULES)
                    .build()),
            new Preset("kingpin", "👑 Kingpin", GameConfig.builder()
                    .maxPlayers(5)
                    .teamCount(0)
                    .worldWidth(1600)
                    .worldHeight(1600)
                    .playerMaxHealth(100)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(KINGPIN_RULES)
                    .build()),
            new Preset("last-stand", "⚔️ Last Stand", GameConfig.builder()
                    .maxPlayers(12)
                    .teamCount(0)
                    .worldWidth(1600)
                    .worldHeight(1600)
                    .playerMaxHealth(100)
                    .aiCheckIntervalMs(10000)
                    .enableAIFilling(true)
                    .rules(LAST_STAND_RULES)
                    .build())
    );

    public static Optional<Preset> getPreset(String id) {
        if (id == null) {
            return Optional.empty();
        }
        return ALL_PRESETS.stream()
                .filter(p -> p.id().equalsIgnoreCase(id))
                .findFirst();
    }
}
